# Generated by Django 3.1.7 on 2021-04-02 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=50)),
                ('clientPhone', models.CharField(max_length=30)),
                ('clientAddres', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original1', models.ImageField(upload_to='img/')),
                ('original2', models.ImageField(upload_to='img/')),
                ('original3', models.ImageField(upload_to='img/')),
                ('fake1', models.ImageField(upload_to='img/')),
                ('fake2', models.ImageField(upload_to='img/')),
                ('fake3', models.ImageField(upload_to='img/')),
                ('clientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerk.client')),
            ],
        ),
    ]
