# Generated by Django 3.1.7 on 2021-04-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_client_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='image',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
