# Generated by Django 3.1.7 on 2021-06-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0003_auto_20210402_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientAddres',
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientPhone',
        ),
        migrations.AddField(
            model_name='client',
            name='img1',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='img2',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='img3',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
