# Generated by Django 3.1.7 on 2021-06-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0004_auto_20210629_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='img3',
        ),
    ]
