# Generated by Django 3.1.7 on 2021-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0005_auto_20210629_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
