# Generated by Django 3.1.7 on 2021-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0008_client_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.AddField(
            model_name='client',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='client',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='client',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
