# Generated by Django 3.1.7 on 2021-07-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0009_auto_20210701_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verifiedImg',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
